// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "527eaa4e-c755-44d2-91a1-fabed103dfe6";

const char SSID[] = "THONG_2.4G";                       // Network SSID (name)
const char PASS[] = "12600092";                         // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[] = "9tBi6nPLnUCokcVCy565qndA3";  // Secret device password

void onSPEED1Change();
void onSPEED2Change();
void onSPEED3Change();
void onSwitchChange();
void onWATERChange();

CloudSwitch sPEED1;
CloudSwitch sPEED2;
CloudSwitch sPEED3;
CloudSwitch Switch;
CloudSwitch WATER;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(sPEED1, READWRITE, ON_CHANGE, onSPEED1Change);
  ArduinoCloud.addProperty(sPEED2, READWRITE, ON_CHANGE, onSPEED2Change);
  ArduinoCloud.addProperty(sPEED3, READWRITE, ON_CHANGE, onSPEED3Change);
  ArduinoCloud.addProperty(Switch, READWRITE, 60 * SECONDS, onSwitchChange);
  ArduinoCloud.addProperty(WATER, READWRITE, 60 * SECONDS, onWATERChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
